<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '荣耀版',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '荣耀版',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '无限流量/30天',
    'measure_unit' => '100',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '无限流量/30天',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '试用号/1天',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '试用号/1天',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '5G流量/30天',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '5G流量/30天',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '10G流量/30天',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '10G流量/30天',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '黄金版',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '黄金版',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '10G流量/30天',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '10G流量/30天',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '试用号/1天',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '试用号/1天',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '无限流量/30天',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '无限流量/30天',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '5G流量/30天',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '5G流量/30天',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '旗舰版',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '旗舰版',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '无限流量/30天',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '无限流量/30天',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '10G流量/30天',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '7',
    'name' => '10G流量/30天',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '试用号/1天',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '试用号/1天',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '5G流量/30天',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '5G流量/30天',
  ),
);
?>